export const MOODS = {
    happy: {
        label: 'Happy',
        genre: 'Pop / Dance',
        message: 'Vibes unlocked! ✨',
        playlistId: 'PLkO_w06KID6jZ_Uf1A0uR_e7UvA-R5U-X', // Vibrant Pop
        color: 'from-yellow-400 to-orange-500',
    },
    sad: {
        label: 'Sad',
        genre: 'Lo-fi / Acoustic',
        message: 'Main character arc. 🌧️',
        playlistId: 'PLOzDu-m_pS6eU_F-fL6O3u_A0o9yP5-G7', // Lofi Hip Hop
        color: 'from-blue-600 to-indigo-800',
    },
    angry: {
        label: 'Angry',
        genre: 'Rock / Metal',
        message: 'Power move mode. 🔥',
        playlistId: 'PLo7j_S_uX8pI9o0_z_z_z', // Placeholder, using a generic rock one below
        color: 'from-red-600 to-red-900',
    },
    surprised: {
        label: 'Surprised',
        genre: 'Upbeat / Electronic',
        message: 'Plot twist! 😲',
        playlistId: 'PLkO_w06KID6hG0K_UeG5z8A-K-uA-A-A', // Placeholder
        color: 'from-purple-500 to-pink-500',
    },
    neutral: {
        label: 'Neutral',
        genre: 'Chill / Indie',
        message: 'Zen state achieved. 🍃',
        playlistId: 'PLkO_w06KID6geH8U8U_x_x_x', // Placeholder
        color: 'from-emerald-400 to-cyan-500',
    },
};

// More specific playlist IDs (trying to find common ones)
export const PLAYLISTS = {
    happy: 'PLkO_w06KID6jZ_Uf1A0uR_e7UvA-R5U-X',
    sad: 'PLrO3760_x_x_x', // Will use a better way in the component
    angry: 'PLo7j_S_uX8pI9_0_z_z',
    surprised: 'PLkO_w06KID6hG0K_UeG5z8A-K-uA-A-A',
    neutral: 'PLkO_w06KID6geH8U8U_x_x_x',
};

// Actually, use public YouTube Mixes or popular IDs if possible, or just standard strings
// For MVP, I'll use common search strings/embeds if playlist IDs are flaky.
// Better: Use specific verified IDs.
export const MOOD_CONFIG = {
    happy: {
        songs: [
            { title: 'Jimikki Kammal', artist: 'Velipadinte Pusthakam' },
            { title: 'Kudukku', artist: 'Love Action Drama' },
            { title: 'Karutha Penne', artist: 'Thenmavin Kombathu' },
            { title: 'Thaalatherichavar', artist: 'Romancham' },
            { title: 'Scene Mone', artist: 'Romancham' },
            { title: 'Aasa Kooda', artist: 'Sushin Shyam' },
            { title: 'Shinkari Melam', artist: 'Classic' },
            { title: 'Lajjavathiye', artist: '4 The People' },
            { title: 'Sundari Laila', artist: '2018' },
            { title: 'Ollulleru', artist: 'Ajagajantharam' },
            { title: 'Pistah', artist: 'Neram' },
            { title: 'Maanam Thudukkanu', artist: 'Aaraattu' },
            { title: 'Enne Thallendamma', artist: 'Thallumaala' },
            { title: 'Ole Mele', artist: 'Thallumaala' },
            { title: 'Parudeesa', artist: 'Bheeshma Parvam' },
            { title: 'Aarambham', artist: 'Thallumaala' },
            { title: 'Theythaka', artist: 'Ustad Hotel' },
            { title: 'Ghora Ghora', artist: 'Big B' },
            { title: 'LavaKusha Ayyappantamma', artist: 'Lava Kusha' },
            { title: 'Rathipushpam', artist: 'Bheeshma Parvam' },
            { title: 'Chemmanam', artist: 'Amen' },
            { title: 'Thani Lokah', artist: 'Lokah' },
            { title: 'Chatha Pacha', artist: 'Chatha Pacha' },
            { title: 'Kiliye Kiliye', artist: 'Afrobeat Mix' },
            { title: 'Monica', artist: 'Monica' },
            { title: 'Turbo Jose', artist: 'Turbo' },
            { title: 'Bhoom Chikk Ba Ba', artist: 'Azhakiya Ravanan' },
            { title: 'Pala Palli', artist: 'Kaduva' },
            { title: 'Kannilu Kannilu', artist: 'Lucifer' },
            { title: 'Thiru Thiru', artist: 'Kaduva' },
            { title: 'Aadharanjali', artist: 'Romancham' },
            { title: 'Dhoom Dhaam', artist: 'Dhoom Dhaam' },
            { title: 'Pattuduthu Vannathum', artist: 'Mix' },
            { title: 'Thanananana Penne', artist: 'Upbeat' },
            { title: 'Paranne', artist: 'Koode' },
            { title: 'Tha Na Na', artist: 'Mix' },
            { title: 'Dhrithangapulakithan', artist: 'Mix' },
            { title: 'Nee Njangade', artist: 'Mix' },
            { title: 'Tapp Tapp', artist: 'Mix' },
            { title: 'Illuminati', artist: 'Aavesham' },
            { title: 'Kalapakkaara', artist: 'King of Kotha' },
            { title: 'Armadham', artist: 'Aavesham' },
            { title: 'Malabari Banger', artist: 'Dabzee' },
            { title: 'SAMBAR', artist: 'ThirumaLi' },
            { title: 'Kallu Kudiyan Anthem', artist: 'Classic Mass' },
            { title: 'Freak Penne', artist: 'Oru Adaar Love' },
            { title: 'Appalaale', artist: 'Kanthari' },
            { title: 'Entammede Jimikki', artist: 'Hit' },
            { title: 'Kaathirunnitumn', artist: 'Mix' },
            { title: 'Sundari', artist: 'Hebah' },
        ],
        message: 'ഉങ്ക സ്‌മൈൽ ക്യൂട്ട് ആർക്!!',
        color: 'linear-gradient(135deg, #f6d365 0%, #fda085 100%)',
        icon: 'Sun',
    },
    sad: {
        songs: [
            { title: 'Nee Himamazhayayi', artist: 'Edakkad Battalion 06' },
            { title: 'Akasham Pole', artist: 'Bheeshma Parvam' },
            { title: 'Azhalinte Azhangalil', artist: 'Ayalum Njanum Thammil' },
            { title: 'Mazhaye', artist: 'James & Alice' },
            { title: 'Poomaname', artist: 'Nirakkoottu' },
            { title: 'Khaalbinakame', artist: 'Meow' },
            { title: 'Nilave', artist: 'Spanish Masala' },
            { title: 'Mele Mevum', artist: 'Classic' },
            { title: 'Aakasham Pole', artist: 'Melody' },
            { title: 'Amme Nee Aranennu', artist: 'Soulful' },
            { title: 'Mazhamegham', artist: 'Rainy Mix' },
            { title: 'Lost Love', artist: 'Abhilasham' },
            { title: 'En Uyire', artist: 'Melody' },
            { title: 'Aayiram Chiraathukal', artist: '2018' },
            { title: 'Thoraathe (Reprise)', artist: 'Sad Version' },
            { title: 'Thiramaalayaay', artist: 'Oh Meri Laila' },
            { title: 'Ithile Thiraye', artist: 'ID - The Fake' },
            { title: 'Akalumbol', artist: 'Mazhayathu' },
            { title: 'Irul Veenurugum', artist: 'Soulful' },
            { title: 'Manju Kaalam', artist: 'Finals' },
            { title: 'Marala', artist: 'Oshana' },
            { title: 'Neerume Kattum', artist: 'Sad' },
            { title: 'Oru Pakalin', artist: 'Sad' },
            { title: 'Neeyam Sooryan', artist: 'Sad' },
            { title: 'Ni Neela vaanam', artist: 'Sad' },
            { title: 'En Jeevane', artist: 'Devadoothan' },
            { title: 'Aatmavil', artist: 'Mazhayethum Munpe' },
            { title: 'Akaleyanengilum', artist: 'Praja' },
            { title: 'Attirambil', artist: 'Mannar Mathai Speaking' },
            { title: 'Ennu Varum Nee', artist: 'Kannaki' },
            { title: 'Gopike', artist: 'Nandanam' },
            { title: 'Hrudaya Sakhi', artist: 'Vellithira' },
            { title: 'Kadalkkaattin', artist: 'Friends' },
            { title: 'Kalippattamai', artist: 'Kalippaattom' },
            { title: 'Kathiripoo', artist: 'Krishnagudiyil Oru Pranayakalathu' },
            { title: 'Marakkam', artist: 'Swapnakkoodu' },
            { title: 'Mayajaalame', artist: 'Sarvam Maya' },
            { title: 'Malare Reprise', artist: 'Premam' },
            { title: 'Mandhara Malaril', artist: 'Sad' },
            { title: 'Varuvaanillaarume', artist: 'Manichithrathazhu' },
            { title: 'Kanneer Poovinte', artist: 'Kireedam' },
            { title: 'Poonkaattinodum', artist: 'Sad' },
            { title: 'Thaliraninjoru Kilimarathile', artist: 'Sad' },
            { title: 'Manju mazha', artist: 'Aagathan' },
            { title: 'Akale', artist: 'Akale' },
            { title: 'Thaniye Mizhikal', artist: 'Guppy' },
            { title: 'Hridayathin Niramaayi', artist: 'Sad' },
            { title: 'Shyamambaram', artist: 'Sad' },
            { title: 'Nilaavil Ellame', artist: 'Sad' },
            { title: 'Jupiter Mazha', artist: 'Sad' },
            { title: 'Malare Ninne', artist: 'Premam' },
            { title: 'Poomuthole', artist: 'Joseph' },
            { title: 'Manjal Prasadavum', artist: 'Nakhakshathangal' },
        ],
        message: 'എന്താ മോനെ ഡിപ്രെഷൻ ആണോ...',
        color: 'linear-gradient(135deg, #1e3a8a 0%, #312e81 100%)',
        icon: 'CloudRain',
    },
    angry: {
        songs: [
            { title: 'Bheeshma Parvam Theme', artist: 'Sushin Shyam' },
            { title: 'Lucifer Theme', artist: 'Deepak Dev' },
            { title: 'Aaraattu Theme', artist: 'Rahul Raj' },
            { title: 'Ranam Title Track', artist: 'Jakes Bejoy' },
            { title: 'Thee jwalakal', artist: 'Angamaly Diaries' },
            { title: 'Manjabi', artist: 'Mass' },
            { title: 'Rukmangadhavidhi', artist: 'Rap' },
            { title: 'Unstoppable', artist: 'Energy' },
            { title: 'Bheeshma Be Notorious', artist: 'Mass' },
            { title: 'Aatuthottil', artist: 'Mass Beats' },
            { title: 'Pokkiri Raja Theme', artist: 'Pokkiri Raja' },
            { title: 'Pulimurugan Theme', artist: 'Pulimurugan' },
            { title: 'Kammattipaadam Theme', artist: 'Kammattipaadam' },
            { title: 'Shaji Pappan BGM', artist: 'Aadu 2' },
            { title: 'Derick Abraham BGM', artist: 'Abrahaminte Santhathikal' },
            { title: 'Anjam Pathira Theme', artist: 'Anjam Pathira' },
            { title: 'Ayyappanum Koshiyum BGM', artist: 'Jakes Bejoy' },
            { title: 'B Tech BGM', artist: 'Mass' },
            { title: 'CIA Climax BGM', artist: 'Gopi Sundar' },
            { title: 'Godha BGM', artist: 'Shaan Rahman' },
            { title: 'Joji BGM', artist: 'Justin Varghese' },
            { title: 'Kammara Sambavam Theme', artist: 'Gopi Sundar' },
            { title: 'Kadavule Pole BGM', artist: 'Lucifer' },
            { title: 'Mikhael BGM', artist: 'Gopi Sundar' },
            { title: 'Minnal Murali Theme', artist: 'Sushin Shyam' },
            { title: 'Rakshasi', artist: 'Nammal' },
            { title: 'Para Para', artist: 'Angry' },
            { title: 'Parava Revenge Theme', artist: 'Rex Vijayan' },
            { title: 'Path of Lakshmana', artist: 'Angry' },
            { title: 'Porinju Mariyam Jose Theme', artist: 'Jakes Bejoy' },
            { title: 'Kalippu', artist: 'Premam' },
            { title: 'Karinthol', artist: 'RRR' },
            { title: 'David Nainan BGM', artist: 'The Great Father' },
            { title: 'Tiyan Aslam Theme', artist: 'Gopi Sundar' },
            { title: 'Varathan Red is on', artist: 'Sushin Shyam' },
            { title: 'Yodha Theme', artist: 'A.R. Rahman' },
            { title: 'Monster Theme', artist: 'Mass' },
            { title: 'Christopher Theme', artist: 'Mass' },
            { title: 'King of Kotha Theme', artist: 'Jakes Bejoy' },
            { title: 'Kaduva Theme', artist: 'Mass' },
            { title: 'Big B Theme', artist: 'Gopi Sundar' },
            { title: 'Sagar Elias Jacky Theme', artist: 'Gopi Sundar' },
            { title: 'Malik BGM', artist: 'Sushin Shyam' },
            { title: 'Trance BGM', artist: 'Jackson Vijayan' },
            { title: 'Kurup Theme', artist: 'Sushin Shyam' },
            { title: 'Salute Theme', artist: 'Jakes Bejoy' },
            { title: 'CBI 5 Theme', artist: 'Jakes Bejoy' },
            { title: 'Jana Gana Mana Theme', artist: 'Jakes Bejoy' },
            { title: 'Fish Rock', artist: 'Thaikkudam Bridge' },
            { title: 'Navarasam', artist: 'Thaikkudam Bridge' },
        ],
        message: 'ഉഫ് നീ സീൻ ആട ഉവ്വേ!!',
        color: 'linear-gradient(135deg, #7f1d1d 0%, #450a0a 100%)',
        icon: 'Zap',
    },
    surprised: {
        songs: [
            { title: 'Thattassery Koottam', artist: 'Upbeat' },
            { title: 'Chinnu Chinnu', artist: 'Ramji Rao Speaking' },
            { title: 'Aasa Kooda (Surprise Mix)', artist: 'Surprise Mix' },
            { title: 'Thara-dhritha-pulakithan', artist: 'Upbeat' },
            { title: 'Mera Naam Shaji Theme', artist: 'Fun' },
            { title: 'Oru Naal', artist: 'Big B' },
            { title: 'Chundari Penne', artist: 'Charlie' },
            { title: 'Ethrayo Janmamayi (Surprise Remix)', artist: 'Surprise Remix' },
            { title: 'Kilukil Pambaram', artist: 'Kilukkam' },
            { title: 'Chandanamani Vaathil (Electronic)', artist: 'Electronic' },
            { title: 'Sundari (Remix)', artist: 'Remix' },
            { title: 'Pavizhamalli (Upbeat)', artist: 'Upbeat' },
            { title: 'Karutha Penne (Trap Mix)', artist: 'Trap Mix' },
            { title: 'Shinkari Melam (Electronic)', artist: 'Electronic' },
            { title: 'Parande (Upbeat)', artist: 'Upbeat' },
            { title: 'Oru Maura Mix', artist: 'Fun' },
            { title: 'Chill Chill (Electronic)', artist: 'Electronic' },
            { title: 'Vathikkalu Vellaripravu (Upbeat)', artist: 'Upbeat' },
            { title: 'Kalakkatha', artist: 'Ayyappanum Koshiyum' },
            { title: 'Malare (Trap)', artist: 'Trap' },
            { title: 'Premam BGM (Electronic)', artist: 'Electronic' },
            { title: 'Hey Pillagaada (Mix)', artist: 'Mix' },
            { title: 'Aalolam (Mix)', artist: 'Mix' },
            { title: 'Chirakukal (Mix)', artist: 'Mix' },
            { title: 'Maane (Mix)', artist: 'Mix' },
            { title: 'Thallumaala Anthem', artist: 'Thallumaala' },
            { title: 'Romancham BGM', artist: 'Sushin Shyam' },
            { title: 'Falimy BGM', artist: 'Vishnu Vijay' },
            { title: 'Rdx Theme', artist: 'Sam C.S.' },
            { title: 'King of Kotha (Electronic)', artist: 'Electronic' },
            { title: 'Band Theme', artist: 'Hridayam' },
            { title: 'Onakka Munthiri', artist: 'Hridayam' },
            { title: 'Darshana (Upbeat)', artist: 'Upbeat' },
            { title: 'Manavalan Thug', artist: 'Thallumaala' },
            { title: 'Kaithapoo (Mix)', artist: 'Mix' },
            { title: 'Vazhiye (Mix)', artist: 'Mix' },
            { title: 'Uyire (Electronic)', artist: 'Electronic' },
            { title: 'Nee (Surprise)', artist: 'Surprise' },
            { title: 'Pathu Kalpanakal (Mix)', artist: 'Mix' },
            { title: 'Minnal Theme', artist: 'Minnal Murali' },
            { title: 'Kabilane', artist: 'Mix' },
            { title: 'Manthra', artist: 'Mix' },
            { title: 'Oorila Oru', artist: 'Mix' },
            { title: 'Tharikida', artist: 'Mix' },
            { title: 'Electronic Vibes', artist: 'Mix' },
            { title: 'Funky Malayali', artist: 'Mix' },
            { title: 'Beat It', artist: 'Mix' },
        ],
        message: 'അട ഗോമ്മലെ!!',
        color: 'linear-gradient(135deg, #7c3aed 0%, #db2777 100%)',
        icon: 'Sparkles',
    },
    neutral: {
        songs: [
            { title: 'Thoraathe', artist: 'Nitin K Siva' },
            { title: 'Pinneyum Pinneyum', artist: 'Krishnagudiyil Oru Pranayakalathu' },
            { title: 'Vathilil', artist: 'Ustad Hotel' },
            { title: 'Eeran Kaattu', artist: 'January Oru Orma' },
            { title: 'Ethra Neramaayi', artist: 'Chill Mix' },
            { title: 'Sundari', artist: 'Hebah' },
            { title: 'Mizhiyil Mayanhadhi', artist: 'Chill' },
            { title: 'Pavizha Mazhaye', artist: 'Athiran' },
            { title: 'Pranayam', artist: 'Relax' },
            { title: 'Olichirikkaan Vallikkudilonnu', artist: 'Aramana Vettile Athidikal' },
            { title: 'Oru Kari Mukilin', artist: 'Vettam' },
            { title: 'Kaathirunnu Kaathirunnu', artist: 'Ennu Ninte Moideen' },
            { title: 'Mounam Swaramayi', artist: 'Aayushkalam' },
            { title: 'KAAYI', artist: 'Baby Jean' },
            { title: 'Kannodu (Live)', artist: 'Job Kurian' },
            { title: 'Kaanan Thonnununde', artist: 'Siddharth Menon' },
            { title: 'Chekuthan', artist: 'Nihal Sadiq' },
            { title: 'La Vida', artist: 'Dabzee' },
            { title: 'Ajitha Hare', artist: 'Gowry Lekshmi' },
            { title: 'Open Your Wings', artist: 'MC Mushti' },
            { title: 'Khalbum Katti', artist: 'Dabzee' },
            { title: 'Panipaali-2', artist: 'NJ' },
            { title: 'Veyil', artist: 'Aromal Chekaver' },
            { title: 'PANIPAALI', artist: 'NJ' },
            { title: 'Chekele', artist: 'Avial' },
            { title: 'Naadan Vibe', artist: 'Indie' },
            { title: 'Jaana Mere Jaana', artist: 'Dabzee' },
            { title: 'Nada Nada', artist: 'Avial' },
            { title: 'Thaalam', artist: 'Indie' },
            { title: 'Khalbhinte Theerath', artist: 'Indie' },
            { title: 'Parayuvaitharuvan', artist: 'Neelakasham Pachakadal Chuvanna Bhoomi' },
            { title: 'Uyiril Thodu', artist: 'Kumbalangi Nights' },
            { title: 'Aaradhike', artist: 'Ambili' },
            { title: 'Jeevamshamayi', artist: 'Theevandi' },
            { title: 'Mizhiyil (Chill)', artist: 'Maya' },
            { title: 'Neeyum Njanum', artist: 'Chill' },
            { title: 'Oru Rathri Koodi', artist: 'Summer in Bethlehem' },
            { title: 'Vennila Chandana Kinnam', artist: 'Azakiya Ravanan' },
            { title: 'Thumbayum Thulasiyum', artist: 'Chill' },
            { title: 'Swapnam', artist: 'Chill' },
            { title: 'Nizhal', artist: 'Chill' },
            { title: 'Kaatrin Mozi', artist: 'Chill' },
            { title: 'Mazhaye', artist: 'Indie' },
            { title: 'Puthumazhayai', artist: 'Charlie' },
            { title: 'Vadakkudikkiloru', artist: 'Meppadiyan' },
            { title: 'Raaman Thedum', artist: 'Ramante Edanthottam' },
            { title: 'Oru Swapnam Pole', artist: 'Swapnam' },
            { title: 'Chill Out', artist: 'Mix' },
            { title: 'Late Night Loft', artist: 'Indie' },
            { title: 'Indie Vibe', artist: 'Indie' },
        ],
        message: 'നീയാരാ  ഫ്രണ്ട്‌സ് ഫിലിമിലെ ജയറാമോ??',
        color: 'linear-gradient(135deg, #10b981 0%, #06b6d4 100%)',
        icon: 'Leaf',
    },
};
